"""Draws every texture of the mod from scratch (no game assets are used).

Each item sprite is a 16x16 region mask (which pixel belongs to which material). Shading and
outlines are added automatically, so one mask gives a different item for each colour set.
"""
import os, sys
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import spec
ASSET_DIR = os.path.dirname(HERE) + '/src/main/resources/assets/combinator'

def hx(c):
    c = c.lstrip('#')
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16), 255)

# ramp = outline, shadow, base, light
RAMPS = {k: [hx(c) for c in v] for k, v in {
    'iron':       ['#26262e', '#6a6a78', '#b0b0bd', '#ececf4'],
    'diamond':    ['#0b3940', '#1c9299', '#49dccf', '#c8fff6'],
    'gold':       ['#5c3b00', '#c7860e', '#f6cf38', '#fff8a6'],
    'redstone':   ['#3d0000', '#9c1212', '#e63030', '#ff8f80'],
    'fire':       ['#5c1600', '#d9480f', '#ff9a1f', '#ffe36b'],
    'magma':      ['#190d08', '#5c2a14', '#b54a12', '#ff8f2c'],
    'ice':        ['#1b3c63', '#4c8ad2', '#9ad0ff', '#ecf8ff'],
    'venom':      ['#10300a', '#2e7b1b', '#62c730', '#c8f66c'],
    'wither':     ['#08080a', '#24242a', '#45454d', '#75757e'],
    'thunder':    ['#5c4b00', '#c6a700', '#ffe83a', '#fffcc9'],
    'blood':      ['#2d0008', '#780e1e', '#c11e36', '#f26c7c'],
    'ender':      ['#0a2a29', '#15786c', '#2ed0b7', '#b6fff1'],
    'void':       ['#0c0517', '#29134f', '#5a2ea7', '#a87af2'],
    'wind':       ['#35565a', '#8ec3c6', '#d5f3f1', '#ffffff'],
    'slime':      ['#1d4811', '#4d982b', '#8ddf49', '#d7ff9c'],
    'cactus':     ['#0d3114', '#1e692b', '#3e9f46', '#8dd98b'],
    'netherite':  ['#121014', '#2e292f', '#4b434c', '#7c707b'],
    'copper':     ['#3c190b', '#994925', '#df7849', '#ffb992'],
    'wood':       ['#291808', '#5a3818', '#8e612f', '#c59b5b'],
    'bone':       ['#484434', '#a7a189', '#e3dec7', '#ffffff'],
    'emerald':    ['#053119', '#118843', '#2ed572', '#a9ffcb'],
    'prismarine': ['#0a3836', '#29887e', '#62d0bc', '#c9fff3'],
    'wheat':      ['#493407', '#a2771b', '#dbb149', '#fbe69b'],
    'meat':       ['#3a1408', '#7d3418', '#b85a2c', '#e39a62'],
    'leather':    ['#2e1a0c', '#6b3f1f', '#a0663a', '#cf9a6a'],
    'stone':      ['#232327', '#55555c', '#8a8a90', '#c2c2c8'],
    'flint':      ['#0e0e12', '#2b2d33', '#4a4d55', '#8a8e99'],
    'lapis':      ['#0b1a4a', '#1f3fa3', '#3d68e0', '#9bb6ff'],
}.items()}

# fixed-material letters usable inside any mask
FIXED = {'I': 'iron', 'W': 'wood', 'G': 'gold', 'R': 'redstone', 'B': 'bone', 'K': 'netherite', 'Y': 'thunder',
         'C': 'ice', 'F': 'fire', 'E': 'emerald', 'V': 'void', 'M': 'meat', 'L': 'leather', 'D': 'diamond',
         'S': 'slime', 'N': 'wind', 'O': 'copper', 'T': 'wheat', 'X': 'blood', 'Z': 'wither', 'U': 'venom', 'Q': 'magma'}

M = {}   # template name -> 16 rows

def T(name, art):
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16, (name, len(rows))
    for r in rows:
        assert len(r) == 16, (name, r, len(r))
    M[name] = rows

# ------------------------------------------------------------------ tools
T('pickaxe', '''
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPP....WPPPP..
.........WWPPPP.
........WWW.PPP.
.......WWW..PPP.
......WWW...PPP.
.....WWW.....PP.
....WWW......PP.
...WWW.......PP.
..WWW.........P.
.WWW............
.WW.............
................
................
''')
T('hammer', '''
................
....PPP.........
...PPPPP........
...PPPPPP.......
....PPPPPP......
.....PPAPPP.....
......PPAPPP....
.....WWPPPPPP...
....WWW.PPPPPP..
...WWW...PPPPP..
..WWW.....PPPP..
.WWW.......PP...
.WW.............
................
................
................
''')
T('drill', '''
................
.............A..
...........AAA..
..........AIAA..
.........AAIA...
........AIAAA...
.......AAAIA....
.....PPPAAA.....
....PPPPPA......
...PPKKPPP......
..PPPKKPPP......
..PPPPPPP.......
.WWPPPPP........
.WW.PPP.........
................
................
''')
T('paxel', '''
................
...PPP..PPPP....
..PPPPPPPPPPP...
..PPPPPPPWPPPP..
..PPPPPPWWWPPP..
..PPPP.WWW.PPP..
...PP.WWW...PP..
.....WWW....PP..
....WWW......P..
...WWW..........
..WWW...........
.WWW............
.WW.............
................
................
................
''')
T('axe', '''
................
........PPPP....
.......PPPPPP...
......PPPPPPPP..
.....PPPPPPPPP..
.....PPPPWPPPP..
......PPWWWPPP..
.......WWW.PP...
......WWW.......
.....WWW........
....WWW.........
...WWW..........
..WWW...........
.WWW............
.WW.............
................
''')
T('battleaxe', '''
................
....PP....PP....
...PPPP..PPPP...
..PPPPPAAPPPPP..
..PPPPPAAPPPPP..
..PPPPPWWPPPPP..
...PPP.WW.PPP...
....P..WW..P....
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......WW.......
.......AA.......
.......AA.......
................
''')
T('shovel', '''
................
............PP..
..........PPPPP.
.........PPPPPP.
........PPPAPPP.
.......PPPAPPP..
.......PPAPPP...
......WWPPPP....
.....WWW.PP.....
....WWW.........
...WWW..........
..WWW...........
.WWW............
.AA.............
................
................
''')
T('hoe', '''
................
.......PPPPPP...
......PPPPPPPP..
......PP..WPPP..
.........WWW....
........WWW.....
.......WWW......
......WWW.......
.....WWW........
....WWW.........
...WWW..........
..WWW...........
.WWW............
.AA.............
................
................
''')
T('scythe', '''
................
....PPPPPPPP....
..PPPPPPPPPPW...
.PPPP.....WWW...
.PP......WWW....
.P......WWW.....
.......WWW......
......AWW.......
.....WAA........
....WWW.........
...WWW..........
..WWW...........
.WWW............
.WW.............
................
................
''')
# ------------------------------------------------------------------ swords
T('sword', '''
................
.............PP.
............PPP.
...........PPPP.
..........PPPP..
.........PPPP...
........PPPP....
..A....PPPP.....
..AA..PPPP......
...AAPPPP.......
....AAPP........
...WWAA.........
..WWW.AA........
.AWW...A........
.AA.............
................
''')
T('sword_split', '''
................
.............PA.
............PPA.
...........PPAA.
..........PPAA..
.........PPAA...
........PPAA....
..K....PPAA.....
..KK..PPAA......
...KKPPAA.......
....KKAA........
...WWKK.........
..WWW.KK........
.GWW...K........
.GG.............
................
''')
T('sword_rainbow', '''
................
.............YY.
............YYY.
...........CCCY.
..........CCCC..
.........FFCC...
........FFFF....
..G....NFFF.....
..GG..NNNF......
...GGNNNN.......
....GGNN........
...VVGG.........
..VVV.GG........
.GVV...G........
.GG.............
................
''')
T('greatsword', '''
..............P.
............PPP.
...........PPPP.
..........PPPPP.
.........PPPPP..
........PPPPP...
.......PPPPP....
.A....PPPPP.....
.AA..PPPPP......
..AAPPPPP.......
...AAPPP........
..WWAAA.........
.WWW.AAA........
AWW....A........
AA..............
................
''')
T('saber', '''
................
...........PPP..
..........PPPP..
.........PPPPP..
.........PPPP...
........PPPP....
........PPP.....
.......PPPP.....
......PPPP......
..AA.PPPP.......
...AAPPP........
...WAAP.........
..WWWAA.........
.AWW............
.AA.............
................
''')
T('cleaver', '''
................
.......PPPPPPPP.
......PPPPPPPPP.
.....PPPPPPPAPP.
.....PPPPPPPPPP.
.....PPPPPPPPP..
.....PPPPPPPP...
.....IIIIIII....
......IIIII.....
.....WW.........
....WWW.........
...WWW..........
..WWW...........
.AWW............
.AA.............
................
''')
T('bat', '''
................
...........PPP..
..........PPPPP.
.........PPPPPP.
........PPPPPPP.
.......PPPPPPP..
......PPPPPPP...
.....PPPPPPP....
....APPPPPP.....
...AAAPPPP......
...WAAAP........
..WWWA..........
.WWW............
.WW.............
................
................
''')
# ------------------------------------------------------------------ gadgets
T('staff', '''
................
...........AAA..
..........AAAAA.
..........AAAAA.
.........PAAAAA.
........PPPAAA..
.......PPP......
......PPP.......
.....PPP........
....PPP.........
...PPP..........
..PPP...........
.PPP............
.PP.............
................
................
''')
T('staff3', '''
.........A...A..
..........AAA...
.........AGGGA..
.........AGGGA..
.........PGGGA..
........PPPAA.A.
.......PPP......
......APP.......
.....PPA........
....PPP.........
...APP..........
..PPA...........
.PPP............
.PP.............
................
................
''')
T('wand', '''
................
............A...
...........AAA..
..........AAAAA.
...........AAA..
..........P.A...
.........PP.....
........PP......
.......PP.......
......PP........
.....PP.........
....PP..........
...PP...........
..PP............
................
................
''')
T('magnet', '''
................
................
...PPPP..PPPP...
...PPPP..PPPP...
...AAAA..AAAA...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
....PPPPPPPP....
.....PPPPPP.....
................
................
................
''')
T('compass', '''
................
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPPBBBBBBPPP..
..PPBBBBARBBPP..
.PPBBBBAABBBBPP.
.PPBBBAAABBBBPP.
.PPBBBBAAABBBPP.
.PPBBBBAABBBBPP.
..PPBBRABBBBPP..
..PPPBBBBBBPPP..
...PPPPPPPPPP...
.....PPPPPP.....
................
................
''')
T('clock', '''
................
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPPBBBABBPPP..
..PPBBBBABBBPP..
.PPBBBBBABBBBPP.
.PPBBBBBABBBBPP.
.PPBBBBBAAAABPP.
.PPBBBBBBBBBBPP.
..PPBBBBBBBBPP..
..PPPBBBBBBPPP..
...PPPPPPPPPP...
.....PPPPPP.....
................
................
''')
T('dynamite', '''
................
............Y...
...........W....
..........W.....
.........PPP....
........PPPPP...
.......PPPPPPP..
......PPAAPPPP..
.....PPPPAAPPP..
....PPPPPPAAP...
...PPAAPPPPP....
...PPPAAPPP.....
...PPPPAAP......
....PPPPP.......
.....PPP........
................
''')
T('pouch', '''
................
................
......LLLL......
.....LL..LL.....
.....GGGGGG.....
....PPPPPPPP....
...PPPPPPPPPP...
..PPPPPAAPPPPP..
..PPPPAAAAPPPP..
..PPPPAAAAPPPP..
..PPPPPAAPPPPP..
..PPPPPPPPPPPP..
...PPPPPPPPPP...
....PPPPPPPP....
................
................
''')
T('workbench', '''
................
................
....LLLLLLLL....
....L......L....
..PPPPPPPPPPPP..
..PAAPPAAPPAAP..
..PAAPPAAPPAAP..
..PPPPPPPPPPPP..
..PAAPPAAPPAAP..
..PAAPPAAPPAAP..
..PPPPPPPPPPPP..
..PPWWWWWWWWPP..
..PPWWWWWWWWPP..
..PPPPPPPPPPPP..
................
................
''')
T('charm', '''
................
.....PPPPPP.....
....PP....PP....
....P......P....
....P......P....
....PP....PP....
.....PPPPPP.....
......PPPP......
.....PAAAAP.....
....PAAAAAAP....
....PAAAAAAP....
....PAAAAAAP....
.....PAAAAP.....
......PPPP......
................
................
''')
T('charm2', '''
................
.....GGGGGG.....
....GG....GG....
....G......G....
....G......G....
....GG....GG....
.....GGGGGG.....
.....GPPAAG.....
....GPPPAAAG....
...GPPPPAAAAG...
...GPPPPAAAAG...
...GPPPPAAAAG...
....GPPPAAAG....
.....GPPAAG.....
......GGGG......
................
''')
T('charm3', '''
.......GG.......
.....GGGGGG.....
....GG....GG....
....G......G....
....GG....GG....
..G..GGGGGG..G..
.GG.GGFFCCGG.GG.
..GGFFFFCCCCGG..
...GFFFAACCCG...
...GEEAAAAVVG...
...GEEEAAVVVG...
..GGEEEEVVVVGG..
.GG.GGEEVVGG.GG.
..G..GGGGGG..G..
.......GG.......
................
''')
T('spyglass', '''
................
...........AAA..
..........AAAAA.
.........PAAAAA.
........PPPAAA..
.......PPPPP....
......GPPPP.....
.....PPGPP......
....PPPPG.......
...GPPPP........
..PPGPP.........
.PPPPG..........
.PPPP...........
..PP............
................
................
''')
T('totem', '''
................
.....PPPPPP.....
....PPPPPPPP....
....PAAPPAAP....
....PAAPPAAP....
....PPPPPPPP....
..PPPPPKKPPPPP..
..PPPPPPPPPPPP..
..PP.PPPPPP.PP..
.....PPAAPP.....
.....PPAAPP.....
.....PPPPPP.....
.....PPPPPP.....
......PPPP......
................
................
''')
# ------------------------------------------------------------------ armor and wings
T('helmet', '''
................
................
....PPPPPPPP....
...PPPPPPPPPP...
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPP......PPP..
..PPP......PPP..
..PPP......PPP..
..PP........PP..
................
................
................
................
''')
T('chestplate', '''
................
..PPP......PPP..
.PPPPP....PPPPP.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPPPAAAAPPPPP.
..PP.PPAAPP.PP..
.....PPPPPP.....
.....PPPPPP.....
.....PPAAPP.....
.....PPPPPP.....
.....PPPPPP.....
.....PPPPPP.....
......PPPP......
................
................
''')
T('leggings', '''
................
................
...PPPPPPPPPP...
...PAAAAAAAAP...
...PPPPPPPPPP...
...PPPPPPPPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPPP..PPPP...
...PPAP..PAPP...
...PPPP..PPPP...
...PPPP..PPPP...
................
................
''')
T('boots', '''
................
................
................
................
..PPPP....PPPP..
..PPPP....PPPP..
..PPPP....PPPP..
..PAAP....PAAP..
..PPPP....PPPP..
..PPPP....PPPP..
.PPPPP....PPPPP.
.PPPPP....PPPPP.
.AAAAA....AAAAA.
................
................
................
''')
T('wings', '''
................
......PPPP......
.....PPAAPP.....
....PPPAAPPP....
...PPPPAAPPPP...
..PPPPP..PPPPP..
..PPPPP..PPPPP..
.PPPPP....PPPPP.
.PPPPP....PPPPP.
.PPPP......PPPP.
.PPPP......PPPP.
.PPP........PPP.
.PPP........PPP.
.PP..........PP.
.P............P.
................
''')
# ------------------------------------------------------------------ food
T('steak', '''
................
................
.....AAAAAA.....
...AAAPPPPAAA...
..AAPPPPPPPPAA..
..APPPPBBPPPPA..
..APPPBBBBPPPA..
..APPPPBBPPPPA..
..AAPPPPPPPPAA..
...AAPPPPPPAA...
....AAAPPAAA....
......AAAA......
................
................
................
................
''')
T('toast', '''
................
................
....PPPPPPPP....
...PPPPPPPPPP...
..PPAAAAAAAAPP..
..PAAAAAAAAAAP..
..PAAAAAAAAAAP..
..PPAAAAAAAAPP..
...PAAAAAAAAP...
...PAAAAAAAAP...
...PAAAAAAAAP...
...PPPPPPPPPP...
................
................
................
................
''')
T('pie', '''
................
................
................
.....AA..AA.....
....PPPPPPPP....
..PPPAPPPPAPPP..
.PPPPPPAAPPPPPP.
.PPAPPPPPPPPAPP.
.PPPPPPPPPPPPPP.
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
...WWWWWWWWWW...
................
................
................
................
''')
T('stew', '''
................
.......F........
......F..F......
.......F.F......
................
..PPPPPPPPPPPP..
.PPAAAAAAAAAAPP.
.PPAAFAAAAFAAPP.
.PPPAAAAAAAAPPP.
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
...PPPPPPPPPP...
....PPPPPPPP....
................
................
................
''')
T('carrot', '''
................
..........A..A..
...........AAA..
..........AAA...
.........PPAAA..
........PPPP.A..
.......PPPPP....
......PPPPP.....
.....PPPPP......
....PPPPP.......
...PPPPP........
..PPPP..........
..PPP...........
..P.............
................
................
''')
T('cookie', '''
................
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPPAPPPPPPPP..
..PPPPPPPAAPPP..
.PPPPPPPPAAPPPP.
.PPAAPPPPPPPPPP.
.PPAAPPPPPPAPPP.
.PPPPPPAPPPPPPP.
..PPPPPPPPPPPP..
..PPPAPPPPAPPP..
...PPPPPPPPPP...
.....PPPPPP.....
................
................
''')
T('sandwich', '''
................
................
....PPPPPPPP....
..PPPPPPPPPPPP..
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.EEEEEEEEEEEEEE.
.AAAAAAAAAAAAAA.
.AAAAAAAAAAAAAA.
.GGGGGGGGGGGGGG.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
..PPPPPPPPPPPP..
................
................
................
''')
T('roll', '''
................
................
................
....PPPPPPPP....
..PPPPPPPPPPPP..
.PPPAAAAAAAAPPP.
.PPAAAXXAAAAAPP.
.PPAAXXXXAAAAPP.
.PPAAAXXAAAAAPP.
.PPPAAAAAAAAPPP.
..PPPPPPPPPPPP..
....PPPPPPPP....
................
................
................
................
''')
T('feast', '''
................
......AAAA......
.....AAAAAA.....
....MMMMMMMM....
...MMMMMMMMMM...
...MMMBMMMMMM...
...MMMMMMBMMM...
....MMMMMMMM....
..PPPPPPPPPPPP..
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
..PPPPPPPPPPPP..
....IIIIIIII....
................
................
................
''')
T('goblet', '''
................
................
...PPPPPPPPPP...
...PAAAAAAAAP...
...PAAAAAAAAP...
...PPAAAAAAPP...
....PPAAAAPP....
.....PPPPPP.....
.......PP.......
.......PP.......
.......PP.......
......PPPP......
.....PPPPPP.....
....PPPPPPPP....
................
................
''')

# ------------------------------------------------------------------ the wild ones
T('raygun', '''
................
................
................
..............A.
.PPPPPPPPPPPPAA.
.PPPPPPPPPPPPAA.
.PPIIPPPPPPPPAA.
..PPPPPPP.....A.
..PPPP..........
..IIPP..........
..III...........
..III...........
..III...........
................
................
................
''')
T('bomb', '''
................
..........Y.....
.........W......
........W.......
.....PPPPPP.....
....PPPPPPPP....
...PPPAAPPPPP...
...PPAAPPPPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
....PPPPPPPP....
.....PPPPPP.....
................
................
''')
T('orb', '''
................
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPPAAPPPPPPP..
..PPAAPPPPPPPP..
.PPPAPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPAPPP.
..PPPPPPPPAAPP..
..PPPPPPPAAPPP..
...PPPPPPPPPP...
.....PPPPPP.....
................
................
''')
T('glove', '''
................
.....P.P.P......
....PPPPPPP.....
....PPPPPPP.P...
....PPPPPPPPP...
....PPPPPPPPP...
....PPPPPPPPP...
....PPPPPPPP....
.....PPPPPPP....
.....PPPPPP.....
.....AAAAAA.....
.....PPPPPP.....
.....PPPPPP.....
.....AAAAAA.....
................
................
''')
T('cake', '''
................
................
.......X........
.......B........
...AAAAAAAAAA...
..AAAAAAAAAAAA..
..PAPPAPPAPPAP..
..PPPPPPPPPPPP..
..TTTTTTTTTTTT..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..TTTTTTTTTTTT..
..TTTTTTTTTTTT..
................
................
................
''')
T('mushroom', '''
................
................
.....PPPPPP.....
...PPPAAPPPPP...
..PPPPAAPPPAPP..
..PAPPPPPPPAPP..
.PPPPPPAPPPPPPP.
.PPPPPPPPPPPPPP.
..PPPPPPPPPPPP..
......BBBB......
......BBBB......
......BBBB......
.....BBBBBB.....
.....BBBBBB.....
................
................
''')
T('chili', '''
................
...........AA...
..........AA....
.........PPA....
........PPPP....
.......PPPPP....
......PPPPPP....
.....PPPPPP.....
....PPPPPP......
...PPPPPP.......
..PPPPPP........
..PPPPP.........
..PPP...........
................
................
................
''')
T('bell', '''
................
.......AA.......
......PPPP......
.....PPPPPP.....
....PPPPPPPP....
....PPPPPPPP....
....PPPPPPPP....
...PPPPPPPPPP...
...PPPPPPPPPP...
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
.PPPPPPPPPPPPPP.
.......AA.......
.......AA.......
................
................
''')
T('horn', '''
................
............PP..
...........PPP..
..........PPPP..
.........PPPP...
........PPPP....
.......PPPP.....
.....APPPP......
....AAPPP.......
...PPAAP........
..PPPPA.........
..PPPP..........
..PPP...........
................
................
................
''')
T('cloak', '''
................
.....AAAAAA.....
....PPAAAAPP....
...PPPPAAPPPP...
...PPPPPPPPPP...
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPP.PPPP.PPPP.
.PP...PP....PPP.
................
................
''')
T('hole', '''
................
................
................
....AAAAAAAA....
..AAAPPPPPPAAA..
.AAPPPPPPPPPPAA.
.APPPPPPPPPPPPA.
.APPPPPPPPPPPPA.
.AAPPPPPPPPPPAA.
..AAAPPPPPPAAA..
....AAAAAAAA....
................
................
................
................
................
''')
T('box', '''
................
................
..AAAAAAAAAAAA..
..APPPPPPPPPPA..
..AAAAAAAAAAAA..
..PPPPPGGPPPPP..
..PPPPPGGPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..AAAAAAAAAAAA..
................
................
................
''')
T('belt', '''
................
................
................
................
................
.PPPPPPPPPPPPPP.
.PPPPPAAAAPPPPP.
.PPPPPAIIAPPPPP.
.PPPPPAIIAPPPPP.
.PPPPPAAAAPPPPP.
.PPPPPPPPPPPPPP.
................
................
................
................
................
''')
T('heart', '''
................
................
...PPP....PPP...
..PPPPP..PPPPP..
.PPAPPPPPPPPPPP.
.PAAPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
.PPPPPPPPPPPPPP.
..PPPPPPPPPPPP..
...PPPPPPPPPP...
....PPPPPPPP....
.....PPPPPP.....
......PPPP......
.......PP.......
................
................
''')
T('book', '''
................
................
...PPPPPPPPPP...
..PPPPPPPPPPPB..
..PPPAAAAPPPPB..
..PPPAAAAPPPPB..
..PPPPPPPPPPPB..
..PPPPPPPPPPPB..
..PPPPPPPPPPPB..
..PPPPPPPPPPPB..
..PPPPPPPPPPPB..
..PPPPPPPPPPPB..
..PBBBBBBBBBBB..
...PPPPPPPPPP...
................
................
''')
T('mirror', '''
................
.....PPPPPP.....
....PAAAAAAP....
...PAAAAAAAAP...
...PAABAAAAAP...
...PABAAAAAAP...
...PAAAAAAAAP...
...PAAAAAAAAP...
....PAAAAAAP....
.....PPPPPP.....
.......PP.......
.......WW.......
.......WW.......
.......WW.......
................
................
''')


# ------------------------------------------------------------------ everyday items (wood, stone, gold, iron)
T('pole', '''
................
............AA..
...........AAA..
...........PA...
..........PP....
.........PP.....
........PP......
.......AA.......
......AA........
.....PP.........
....PP..........
...PP...........
..AP............
.AAA............
.AA.............
................
''')
T('jagged', '''
................
.............PP.
............PPP.
..........P.PP..
.........PPPP...
........P.PP....
.......PPPP.....
..A...P.PP......
..AA.PPPP.......
...AAPPP........
....AAP.........
...WWAA.........
..WWW.AA........
.AWW...A........
.AA.............
................
''')
T('twin', '''
................
..PP.........PP.
..PPP.......PPP.
...PPP.....PPP..
....PPP...PPP...
.....PPP.PPP....
......PPPPP.....
.......PPP......
......PPPPP.....
.....APP.PPA....
....AAA...AAA...
...WWA.....AWW..
..WWW.......WWW.
..WW.........WW.
................
................
''')
T('sickle', '''
................
.....PPPPPP.....
...PPPPPPPPP....
..PPP.....PPP...
..PP.......PPP..
..P.........PP..
............PP..
...........PPP..
..........WPP...
.........WWW....
........WWW.....
.......WWW......
......WWW.......
.....AWW........
.....AA.........
................
''')
T('boomerang', '''
................
................
..PPP...........
..PPPPP.........
...PPPPPP.......
....APPPPPP.....
.....AAPPPPP....
.......APPPP....
........PPPP....
........PPPP....
.......PPPP.....
.......PPPA.....
......PPPAA.....
......PPA.......
......PP........
................
''')
T('bow', '''
................
.........PPPPA..
.......PPP...B..
......PP....B...
.....AA....B....
....AA....B.....
...PP....B......
...P....B.......
..PP...B........
..P...B.........
..P..B..........
..P.B...........
..PB............
..A.............
................
................
''')
T('hook', '''
................
..........P..P..
.........PP.PP..
.........P..P.P.
.........PPPPPP.
..........PPPP..
.........APP....
........AA......
.......WA.......
......WW........
.....WW.........
....WW..TT......
...WW..T..T.....
..WW...T..T.....
........TT......
................
''')
T('lasso', '''
................
....PPPPPP......
...PP....PP.....
..PP......PP....
..P........P....
..P........P....
..PP......PP....
...PP....PPA....
....PPPPPPAA....
.........AAP....
..........PP....
...........PP...
............PP..
.............PP.
..............P.
................
''')
T('rod', '''
................
...........PP...
..........PPB...
.........PP.B...
........PP..B...
.......PP...B...
......PP....B...
.....PP.....B...
....PP.....RRR..
...AP......RRR..
..AA.......BBB..
.PA.........B...
.P..............
................
................
................
''')
T('backpack', '''
................
.....AAAAAA.....
....A......A....
...PPPPPPPPPP...
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..AAAAAAAAAAAA..
..PPPPPGGPPPPP..
..PPPPPGGPPPPP..
..PPAAAAAAAAPP..
..PPAPPPPPPAPP..
..PPAPPPPPPAPP..
..PPAAAAAAAAPP..
..PPPPPPPPPPPP..
...PPPPPPPPPP...
................
''')
T('furnace', '''
................
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPZZZZZZZZPP..
..PPZZZZZZZZPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPZZZZZZZZPP..
..PPZAAZZAAZPP..
..PPZAAAAAAZPP..
..PPAAAYYAAAPP..
..PPAAYYYYAAPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
................
................
''')
T('bedroll', '''
................
................
................
....PPPPPPPPP...
...PPPAPPPAPPP..
..PBBPPAPPPAPPP.
..BPPBPAPPPAPPP.
..BPBBPAPPPAPPP.
..BPPBPAPPPAPPP.
..PBBPPAPPPAPPP.
...PPPAPPPAPPP..
....PPPPPPPPP...
................
................
................
................
''')
T('waystone', '''
................
......PPPP......
.....PPPPPP.....
....PPPAAPPP....
....PPAPPAPP....
....PPAPPAPP....
....PPPAAPPP....
....PPPPPPPP....
....PPPAAPPP....
....PPPAAPPP....
....PPPPPPPP....
...PPPPPPPPPP...
..PPPPPPPPPPPP..
..ZZZZZZZZZZZZ..
................
................
''')
T('ladder', '''
................
....P......P....
....PAAAAAAP....
....P......P....
....P......P....
....PAAAAAAP....
....P......P....
....P......P....
....PAAAAAAP....
....P......P....
....P......P....
....PAAAAAAP....
....P......P....
....P......P....
................
................
''')
T('bigshears', '''
................
..PP.......PP...
..PPP.....PPP...
...PPP...PPP....
....PPP.PPP.....
.....PPPPP......
......PIP.......
.....PPPPP......
....AAP.PAA.....
...AA.....AA....
..AA.AA.AA.AA...
..A..AA.AA..A...
..AA.A...A.AA...
...AAA...AAA....
................
................
''')
T('bucket', '''
................
....IIIIIIII....
...I........I...
..I..........I..
..PPPPPPPPPPPP..
..PAAAAAAAAAAP..
..PAAAAAAAAAAP..
...PPPPPPPPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
....PPPPPPPP....
....PPPPPPPP....
....PPPPPPPP....
.....PPPPPP.....
................
................
''')
T('whistle', '''
................
................
...........AA...
..........A..A..
..........A..A..
...........AA...
..PPPPPPPPPP....
.PPPPPPPPPPPP...
.PPZZPPPPPPPP...
.PPZZPPPPPPPP...
.PPPPPPPPPPP....
..PPPPPPP.......
....PPPP........
................
................
................
''')
T('coin', '''
................
................
.....PPPPPP.....
...PPPPPPPPPP...
..PPPAAAAAAPPP..
..PPAPPPPPPAPP..
.PPAPPPAAPPPAPP.
.PPAPPAAAAPPAPP.
.PPAPPAAAAPPAPP.
.PPAPPPAAPPPAPP.
..PPAPPPPPPAPP..
..PPPAAAAAAPPP..
...PPPPPPPPPP...
.....PPPPPP.....
................
................
''')
T('crook', '''
................
........PPPP....
.......PP..PP...
......PP....PP..
......P......P..
......P.....PP..
......PP........
.......PP.......
......APP.......
.....AAP........
....PPA.........
...PPP..........
..PPP...........
.PPP............
.PP.............
................
''')
T('net', '''
................
.......PPPPPP...
......PA.A.A.P..
.....P.A.A.A.P..
.....PA.A.A.AP..
.....P.A.A.A.P..
.....PA.A.A.P...
......PPPPPP....
.....WW.........
....WW..........
...WW...........
..WW............
.WW.............
.W..............
................
................
''')
T('fork', '''
................
..PP.......PP...
..PPP.....PPP...
...PPP...PPP....
....PPP.PPP.....
.....PPPPP......
......PPP.......
......PPP.......
......APA.......
......APA.......
......PPP.......
......PPP.......
......PPP.......
......PP........
................
................
''')
T('cane', '''
................
...........AAA..
..........AAAA..
..........AAA...
.........PP.....
........PPL.....
.......PP.L.....
......PP.LL.....
.....PP.........
....PP..........
...PP...........
..PP............
.PP.............
.P..............
................
................
''')
T('dreamcatcher', '''
................
.....PPPPPP.....
....P.A..A.P....
...P..A..A..P...
...PAAAAAAAAP...
...P..A..A..P...
...PAAAAAAAAP...
...P..A..A..P...
....P.A..A.P....
.....PPPPPP.....
....B..B..B.....
....B..B..B.....
...NB.NB.NB.....
...N..N..N......
................
................
''')
T('horseshoe', '''
................
................
....PPP..PPP....
...PPPP..PPPP...
...PAP....PAP...
...PPP....PPP...
...PAP....PAP...
...PPP....PPP...
...PAP....PAP...
...PPPP..PPPP...
....PPPPPPPP....
.....PPAAPP.....
......PPPP......
................
................
................
''')
T('chicken', '''
................
........RR......
.......RRR......
......PPPP......
.....PPZPPYY....
.....PPPPPY.....
....PPPPPPR.....
..PPPPPPPPP.....
.PPPPPPPPPP.....
.PPAAAPPPPP.....
.PPPAAAPPPP.....
..PPPPPPPP......
...PPPPPP.......
....Y..Y........
...YY.YY........
................
''')
T('crown', '''
................
................
................
..P....PP....P..
..PP..PPPP..PP..
..PPP.PPPP.PPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PAAPPAAPPAAP..
..PAAPPAAPPAAP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
................
................
................
................
''')
T('fishchips', '''
................
................
....T.T.T.......
....T.T.T.TPP...
...TT.T.TPPPPP..
...TTTTTPPPZPPP.
...TTTTPPPPPPP..
..ATTTTTPPPPP.A.
..AATTTTTPP.AAA.
..AAAAAAAAAAAA..
...AAAAAAAAAA...
....AAAAAAAA....
................
................
................
................
''')
T('candyapple', '''
................
................
.....PPPPPP.....
....PPPPPPPP....
...PPAAPPPPPP...
...PAAPPPPPPP...
...PAPPPPPPPP...
...PPPPPPPPPP...
...PPPPPPPPPP...
....PPPPPPPP....
.....PPPPPP.....
.......WW.......
.......WW.......
.......WW.......
.......WW.......
................
''')

# ------------------------------------------------------------------ glyphs: small badges with explicit colours
G = {}
def GL(name, art, pal):
    G[name] = ([r for r in art.strip('\n').split('\n')], {k: hx(v) for k, v in pal.items()})
GL('flame', '''
..y..
.yo.y
.oyo.
oyyyo
orrro
.rrr.
''', {'y': '#ffe36b', 'o': '#ff9a1f', 'r': '#d9480f'})
GL('chain', '''
.ll..
l..l.
l.ddl
.ld.d
..d.d
...dd
''', {'l': '#ececf4', 'd': '#8a8a98'})
GL('gem', '''
.ggg.
gwggd
ggggd
.ggd.
..d..
''', {'g': '#2ed572', 'w': '#d8ffe6', 'd': '#118843'})
GL('magnet', '''
rr.rr
rr.rr
ww.ww
rr.rr
rrrrr
.rrr.
''', {'r': '#e63030', 'w': '#ececf4'})
GL('star', '''
..y..
..y..
yywyy
.yyy.
.y.y.
''', {'y': '#ffe83a', 'w': '#ffffff'})
GL('skull', '''
.www.
wwwww
wkwkw
wwwww
.wkw.
.w.w.
''', {'w': '#e3dec7', 'k': '#1a1a1f'})
GL('leaf', '''
...gg
.gggl
ggglg
gglg.
dgg..
d....
''', {'g': '#3e9f46', 'l': '#8dd98b', 'd': '#5a3818'})
GL('bolt', '''
..yy.
.yy..
yyyy.
..yy.
.yy..
.y...
''', {'y': '#ffe83a'})
GL('heart', '''
.r.r.
rprrr
rrrrr
.rrr.
..r..
''', {'r': '#e63030', 'p': '#ffb0b0'})
GL('lamp', '''
.yyy.
ywwwy
ywwwy
.yyy.
''', {'y': '#ffb21f', 'w': '#fff8c9'})
GL('visor', '''
bbbbbb
bwbbbb
bbbbbb
''', {'b': '#4c8ad2', 'w': '#ecf8ff'})
GL('wing', '''
www..
wwww.
.wwww
..www
...ww
''', {'w': '#ffffff'})

GL('anvil', '''
kkkkk
.kkk.
..k..
.kkk.
kkkkk
''', {'k': '#4b434c'})
GL('egg', '''
.ww.
wwww
wwww
wwww
.ww.
''', {'w': '#f3ead2'})
GL('question', '''
.yyy.
y...y
...y.
..y..
.....
..y..
''', {'y': '#ffe83a'})

GL('wool', '''
.ww..
wwwwg
wwwwg
.ggg.
''', {'w': '#ffffff', 'g': '#c9d2d6'})
GL('seed', '''
.g...
ggy..
.gyy.
..y..
''', {'g': '#62c730', 'y': '#dbb149'})
GL('shield', '''
bbbbb
bwwwb
bwwwb
.bwb.
..b..
''', {'b': '#6a6a78', 'w': '#c59b5b'})
GL('arrows', '''
w.w.w
w.w.w
b.b.b
b.b.b
''', {'w': '#ececf4', 'b': '#8e612f'})
GL('paw', '''
.k.k.
k.k.k
.kkk.
.kkk.
''', {'k': '#6b3f1f'})

GLYPH_POS = {'lamp': (5, 4), 'visor': (5, 6), 'wing': (0, 2), 'question': (5, 5)}   # default is bottom-right

def render(template, primary, accent, glyph=None):
    rows = M[template]
    mat = [[None] * 16 for _ in range(16)]
    for y in range(16):
        for x in range(16):
            ch = rows[y][x]
            if ch == '.': continue
            mat[y][x] = primary if ch == 'P' else accent if ch == 'A' else FIXED[ch]
    def at(x, y):
        return mat[y][x] if 0 <= x < 16 and 0 <= y < 16 else None
    img = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
    px = img.load()
    for y in range(16):
        for x in range(16):
            m = mat[y][x]
            if m is None: continue
            up, left, down, right = at(x, y - 1), at(x - 1, y), at(x, y + 1), at(x + 1, y)
            if up is None or left is None: shade = 3
            elif down is None or right is None: shade = 1
            elif up != m and left != m: shade = 3
            elif down != m and right != m: shade = 1
            else: shade = 2
            px[x, y] = RAMPS[m][shade]
    # outline on the empty pixels around the shape, in the darkest tone of the material it touches
    for y in range(16):
        for x in range(16):
            if mat[y][x] is not None: continue
            for nx, ny in ((x + 1, y), (x, y + 1), (x - 1, y), (x, y - 1)):
                m = at(nx, ny)
                if m is not None:
                    px[x, y] = RAMPS[m][0]
                    break
    if glyph:
        art, pal = G[glyph]
        h, w = len(art), max(len(r) for r in art)
        gx, gy = GLYPH_POS.get(glyph, (15 - w, 15 - h))
        cells = {(gx + i, gy + j): pal[c] for j, r in enumerate(art) for i, c in enumerate(r) if c != '.'}
        for (x, y) in cells:        # dark rim so the badge reads on top of the item
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    q = (x + dx, y + dy)
                    if q not in cells and 0 <= q[0] < 16 and 0 <= q[1] < 16 and abs(dx) + abs(dy) == 1:
                        px[q] = (20, 16, 24, 255)
        for (x, y), c in cells.items():
            if 0 <= x < 16 and 0 <= y < 16: px[x, y] = c
    return img

def sheet(images, labels, path, scale=10, cols=10):
    from PIL import ImageDraw
    cw, chh = 16 * scale + 14, 16 * scale + 22
    rows = (len(images) + cols - 1) // cols
    out = Image.new('RGBA', (cols * cw, rows * chh), (70, 72, 80, 255))
    d = ImageDraw.Draw(out)
    for i, (im, lab) in enumerate(zip(images, labels)):
        x, y = (i % cols) * cw + 7, (i // cols) * chh + 4
        d.rectangle([x, y, x + 16 * scale - 1, y + 16 * scale - 1], fill=(139, 139, 139, 255))
        out.alpha_composite(im.resize((16 * scale, 16 * scale), Image.NEAREST), (x, y))
        d.text((x, y + 16 * scale + 3), lab[:26], fill=(255, 255, 255, 255))
    out.save(path)

if __name__ == '__main__':
    out_dir = ASSET_DIR + '/textures/item'
    os.makedirs(out_dir, exist_ok=True)
    imgs, labs = [], []
    for it in spec.ITEMS:
        t, p, a, g = it['tex']
        im = render(t, p, a, g)
        im.save(f'{out_dir}/{it["id"]}.png')
        imgs.append(im); labs.append(it['id'])
    sheet(imgs, labs, HERE + '/preview_items.png')
    print(len(imgs), 'item textures')


# ====================================================================== block, GUI and icon textures
def _noise(x, y, seed):
    """Small repeatable pseudo-random number 0..99 for subtle texture variation."""
    return ((x * 73856093) ^ (y * 19349663) ^ (seed * 83492791)) % 100

def block_side(front):
    wood, iron, void, dia, gold = RAMPS['wood'], RAMPS['netherite'], RAMPS['void'], RAMPS['diamond'], RAMPS['gold']
    im = Image.new('RGBA', (16, 16)); px = im.load()
    for y in range(16):
        for x in range(16):
            if y == 0: c = iron[3]
            elif y == 1: c = iron[2]
            elif y == 2: c = iron[0]
            else:
                c = wood[2]
                n = _noise(x, y, 7 if front else 3)
                if n < 14: c = wood[3]
                elif n > 86: c = wood[1]
                if y in (8, 15): c = wood[0] if y == 15 else wood[1]          # plank seams
                seam = 5 if y < 8 else 10
                if x == seam and y not in (8, 15): c = wood[1]
                if x in (0, 15): c = wood[0]                                    # legs
                elif x in (1, 14): c = wood[1]
            px[x, y] = c
    # purple cloth strip under the metal top
    for x in range(2, 14):
        px[x, 3] = void[2] if x % 2 == 0 else void[1]
    if front:
        # emblem: two small gems, a plus sign and a result gem
        for (x, y, c) in [(3, 6, dia[2]), (4, 6, dia[3]), (3, 7, dia[1]), (4, 7, dia[2]),
                          (3, 11, dia[2]), (4, 11, dia[3]), (3, 12, dia[1]), (4, 12, dia[2]),
                          (7, 9, gold[3]), (8, 9, gold[2]), (9, 9, gold[2]), (10, 9, gold[1]),
                          (9, 8, gold[2]), (9, 10, gold[1]),
                          (12, 8, void[3]), (13, 8, void[2]), (12, 9, void[2]), (13, 9, void[2]),
                          (12, 10, void[2]), (13, 10, void[1]), (11, 9, void[3]), (14, 9, void[1])]:
            px[x, y] = c
    return im

def block_top():
    iron, void, dia, gold = RAMPS['netherite'], RAMPS['void'], RAMPS['diamond'], RAMPS['gold']
    im = Image.new('RGBA', (16, 16)); px = im.load()
    for y in range(16):
        for x in range(16):
            edge = min(x, y, 15 - x, 15 - y)
            if edge == 0: c = iron[0]
            elif edge == 1: c = iron[3] if (x == 1 or y == 1) else iron[1]
            else:
                c = void[1]
                if _noise(x, y, 11) < 18: c = void[2]
            px[x, y] = c
    def slot(x0, y0):
        for y in range(y0, y0 + 4):
            for x in range(x0, x0 + 4):
                inner = x0 < x < x0 + 3 and y0 < y < y0 + 3
                px[x, y] = void[0] if inner else gold[2]
        px[x0, y0] = gold[3]; px[x0 + 3, y0 + 3] = gold[1]
    slot(3, 3); slot(3, 9)
    # arrow to the result gem
    for (x, y) in [(8, 7), (8, 8), (9, 7), (9, 8)]:
        px[x, y] = gold[2]
    for (x, y, c) in [(11, 6, dia[3]), (12, 6, dia[2]), (10, 7, dia[3]), (11, 7, dia[3]), (12, 7, dia[2]), (13, 7, dia[1]),
                      (10, 8, dia[2]), (11, 8, dia[2]), (12, 8, dia[1]), (13, 8, dia[1]), (11, 9, dia[1]), (12, 9, dia[0])]:
        px[x, y] = c
    for (x, y) in [(2, 2), (13, 2), (2, 13), (13, 13)]:
        px[x, y] = iron[3]
    return im

def block_bottom():
    wood = RAMPS['wood']
    im = Image.new('RGBA', (16, 16)); px = im.load()
    for y in range(16):
        for x in range(16):
            c = wood[1]
            n = _noise(x, y, 5)
            if n < 12: c = wood[2]
            if y % 4 == 3 or x in (0, 15) or y in (0,): c = wood[0]
            px[x, y] = c
    return im

def gui():
    W, H = 176, 166
    im = Image.new('RGBA', (256, 256), (0, 0, 0, 0)); px = im.load()
    BASE, LIGHT, DARK, EDGE = hx('#c6c6c6'), hx('#ffffff'), hx('#555555'), hx('#000000')
    SLOT_D, SLOT_L, SLOT_B = hx('#373737'), hx('#ffffff'), hx('#8b8b8b')
    for y in range(H):
        for x in range(W):
            e = min(x, y, W - 1 - x, H - 1 - y)
            if e == 0: c = EDGE
            elif e <= 2: c = LIGHT if (x <= 2 or y <= 2) and not (x >= W - 3 or y >= H - 3) else DARK
            else: c = BASE
            px[x, y] = c
    # rounded corners
    for (x, y) in [(0, 0), (1, 0), (0, 1), (W - 1, 0), (W - 2, 0), (W - 1, 1), (0, H - 1), (1, H - 1), (0, H - 2), (W - 1, H - 1), (W - 2, H - 1), (W - 1, H - 2)]:
        px[x, y] = (0, 0, 0, 0)
    for (x, y) in [(1, 1), (W - 2, 1), (1, H - 2), (W - 2, H - 2)]:
        px[x, y] = EDGE
    px[2, 2] = LIGHT; px[W - 3, H - 3] = DARK; px[W - 3, 2] = BASE; px[2, H - 3] = BASE

    def slot(sx, sy, size=18):
        """sx, sy = top-left of the frame. The item is drawn 1 pixel inside (or centred for the big slot)."""
        for y in range(size):
            for x in range(size):
                if x == size - 1 and y == 0 or x == 0 and y == size - 1: c = SLOT_B
                elif x == 0 or y == 0: c = SLOT_D
                elif x == size - 1 or y == size - 1: c = SLOT_L
                else: c = SLOT_B
                px[sx + x, sy + y] = c
    slot(34, 34); slot(70, 34)
    slot(128, 30, 26)
    for row in range(3):
        for col in range(9):
            slot(7 + col * 18, 83 + row * 18)
    for col in range(9):
        slot(7 + col * 18, 141)
    # plus sign between the two inputs
    PLUS = hx('#5a5a5a')
    for i in range(9):
        for t in (0, 1):
            px[57 + i, 42 + t] = PLUS
            px[60 + t + 0, 39 + i] = PLUS
    # arrow to the result
    ARROW = hx('#8b8b8b'); ARROW_D = hx('#5a5a5a')
    for x in range(96, 112):
        for y in range(41, 46):
            px[x, y] = ARROW
    for i in range(8):
        for y in range(36 + i, 51 - i):
            px[112 + i, y] = ARROW
    for x in range(96, 112):
        px[x, 45] = ARROW_D
    for i in range(8):
        px[112 + i, 50 - i] = ARROW_D
    return im

def write_extra():
    base = ASSET_DIR
    os.makedirs(base + '/textures/block', exist_ok=True)
    os.makedirs(base + '/textures/gui', exist_ok=True)
    front = block_side(True)
    front.save(base + '/textures/block/combiner_table_front.png')
    block_side(False).save(base + '/textures/block/combiner_table_side.png')
    block_top().save(base + '/textures/block/combiner_table_top.png')
    block_bottom().save(base + '/textures/block/combiner_table_bottom.png')
    gui().save(base + '/textures/gui/combiner.png')
    # mod icon: the top of the table, enlarged
    block_top().resize((128, 128), Image.NEAREST).save(base + '/icon.png')
    # preview sheet
    prev = Image.new('RGBA', (16 * 12 * 4 + 50 + 176 * 3, 166 * 3 + 20), (70, 72, 80, 255))
    for i, im in enumerate([front, block_side(False), block_top(), block_bottom()]):
        prev.alpha_composite(im.resize((192, 192), Image.NEAREST), (10 + (i % 2) * 202, 10 + (i // 2) * 202))
    prev.alpha_composite(gui().crop((0, 0, 176, 166)).resize((528, 498), Image.NEAREST), (424, 10))
    prev.save(HERE + '/preview_block_gui.png')

if __name__ == '__main__':
    write_extra()
