# Builds the mod on every push. The finished .jar is attached to the run as "item-combinator-jar".
name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build --stacktrace
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: item-combinator-jar
          path: build/libs/
